{
  "openapi": "3.0.3",
  "info": {
    "title": "Account Service",
    "version": "1.1.3",
    "description": "This spec lists all available endpoints related to the account service.",
    "contact": {
      "name": "Karsten Eugene Lie",
      "email": "karsten.lie@binus.ac.id"
    }
  },
  "servers": [
    {
      "url": "http://localhost:8080/api/v1",
      "description": "AWS",
      "variables": {
        "subdomain": {
          "enum": [
            "dev",
            "prod"
          ],
          "default": "dev"
        }
      }
    },
    {
      "url": "http://localhost:8080/api/v1",
      "description": "GCP",
      "variables": {
        "subdomain": {
          "enum": [
            "dev",
            "prod"
          ],
          "default": "dev"
        }
      }
    }
  ],
  "tags": [
    {
      "name": "Query",
      "description": "All endpoints related to get accounts"
    },
    {
      "name": "Create",
      "description": "All endpoints related to creating accounts"
    },
    {
      "name": "Patch",
      "description": "All endpoints related to updating accounts"
    },
    {
      "name": "Delete",
      "description": "All endpoints related to deleting accounts"
    }
  ],
  "paths": {
    "/students": {
      "get": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Query"
        ],
        "summary": "Get some or all student accounts",
        "responses": {
          "200": {
            "description": "Student accounts to be returned",
            "content": {
              "application/json": {
                "example": [
                  {
                    "binusian_id": "2440035596",
                    "fname": "Darren",
                    "lname": "Pangesa",
                    "email": "darrenpangesa@binus.ac.id",
                    "password": "hello1",
                    "phone_no": "081219201007",
                    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a ligula.",
                    "profile_img": "https://www.youtube.com/shorts/AWOyEIuVzzQ",
                    "class_id": "L5AC"
                  },
                  {
                    "binusian_id": "2440035463",
                    "fname": "Karsten",
                    "lname": "Lie",
                    "email": "karsten.lie@binus.ac.id",
                    "password": "hello2",
                    "phone_no": "082139311197",
                    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a ligula.",
                    "profile_img": "https://www.youtube.com/shorts/AWOyEIuVzzQ",
                    "class_id": "L5AC"
                  },
                  {
                    "binusian_id": "2440032474",
                    "fname": "Ellyz",
                    "lname": "Yaory",
                    "email": "ellyz.yaory@binus.ac.id",
                    "password": "hello3",
                    "phone_no": "087732171711",
                    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a ligula.",
                    "profile_img": "https://www.youtube.com/shorts/AWOyEIuVzzQ",
                    "class_id": "L5AC"
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Create"
        ],
        "summary": "Post a new student account",
        "description": "Create a new student account",
        "requestBody": {
          "required": true,
          "description": "Request body to create a student account",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Students"
              },
              "examples": {
                "single": {
                  "value": 
                    {
                      "binusian_id": "3840000001",
                      "fname": "Anya",
                      "lname": "Forger",
                      "email": "anya.forger@binus.ac.id",
                      "password": "peanut",
                      "phone_no": "082123456789",
                      "description": "Hi! I am a student.",
                      "profile_img": "https://www.youtube.com/shorts/AWOyEIuVzzQ",
                      "class_id": "L1AC"
                    }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Student account is created",
            "content": {
              "application/json": {
                "example": {
                  "message": "The student account was successfully created."
                }
              }
            }
          }
        }
      }
    },
    "/students/{id}": {
       "parameters": [{ 
          "in": "path", 
          "name": "id", 
          "required": true,
          "description": "ID of student to fetch",
          "schema": {
            "type": "string"
          } 
          }],
      "delete": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Delete"
        ],
        "summary": "Delete a student account",
        "description": "Delete a student account",
        "responses": {
          "200": {
            "description": "Student account is deleted",
            "content": {
              "application/json": {
                "example": {
                  "message": "The student account was successfully deleted."
                }
              }
            }
          }
        }
      },
      "patch": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Patch"
        ],
        "summary": "Update a student account",
        "description": "Update a student account",
        "requestBody": {
          "required": true,
          "description": "Request body to update a student account",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Students"
              },
              "examples": {
                "single": {
                  "value": 
                    {
                      "binusian_id": "3840000001",
                      "description": "I like peanuts.",
                      "profile_img": "https://www.youtube.com/shorts/K-RabQ9lPtg"
                    }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Student account is updated",
            "content": {
              "application/json": {
                "example": {
                  "message": "The student account was successfully updated."
                }
              }
            }
          }
        }
      }
    },
    "/lecturers": {
      "get": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Query"
        ],
        "summary": "Get some or all lecturer accounts",
        "responses": {
          "200": {
            "description": "Lecturer accounts to be returned",
            "content": {
              "application/json": {
                "example": [
                  {
                    "binusian_id": "D6405",
                    "fname": "Ardimas",
                    "lname": "Purwita",
                    "email": "ardimas.purwita@binus.ac.id",
                    "password": "hello1",
                    "phone_no": "081112345678",
                    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a ligula.",
                    "profile_img": "https://www.youtube.com/shorts/AWOyEIuVzzQ"
                  },
                  {
                    "binusian_id": "D6211",
                    "fname": "Nunung",
                    "lname": "Qomariyah",
                    "email": "nunung.qomariyah@binus.ac.id",
                    "password": "hello2",
                    "phone_no": "082112345678",
                    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a ligula.",
                    "profile_img": "https://www.youtube.com/shorts/AWOyEIuVzzQ"
                  },
                  {
                    "binusian_id": "D3697",
                    "fname": "Maria",
                    "lname": "Astriani",
                    "email": "maria.astriani@binus.ac.id",
                    "password": "hello3",
                    "phone_no": "083112345678",
                    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a ligula.",
                    "profile_img": "https://www.youtube.com/shorts/AWOyEIuVzzQ"
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Create"
        ],
        "summary": "Post a new lecturer account",
        "description": "Create a new lecturer account",
        "requestBody": {
          "required": true,
          "description": "Request body to create a lecturer account",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Lecturers"
              },
              "examples": {
                "single": {
                  "value": 
                    {
                      "binusian_id": "D9900",
                      "fname": "Loid",
                      "lname": "Forger",
                      "email": "loid.forger@binus.ac.id",
                      "password": "twilight",
                      "phone_no": "084112345678",
                      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a ligula.",
                      "profile_img": "https://www.youtube.com/shorts/AWOyEIuVzzQ"
                    }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Lecturer account is created",
            "content": {
              "application/json": {
                "example": {
                  "message": "The lecturer account was successfully created."
                }
              }
            }
          }
        }
      }
    },
    "/lecturers/{id}": {
      "parameters": [{ 
          "in": "path", 
          "name": "id", 
          "required": true,
          "description": "ID of lecturer to fetch",
          "schema": {
            "type": "string"
          } 
          }],
      "delete": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Delete"
        ],
        "summary": "Delete a lecturer account",
        "description": "Delete a lecturer account",
        "responses": {
          "200": {
            "description": "Lecturer account is deleted",
            "content": {
              "application/json": {
                "example": {
                  "message": "The lecturer account was successfully deleted."
                }
              }
            }
          }
        }
      },
      "patch": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Patch"
        ],
        "summary": "Update a lecturer account",
        "description": "Update a lecturer account",
        "requestBody": {
          "required": true,
          "description": "Request body to update a lecturer account",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Lecturers"
              },
              "examples": {
                "single": {
                  "value": 
                    {
                      "binusian_id": "D9900",
                      "description": "I am not a spy.",
                      "profile_img": "https://www.youtube.com/shorts/K-RabQ9lPtg"
                    }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Lecturer account is updated",
            "content": {
              "application/json": {
                "example": {
                  "message": "The lecturer account was successfully updated."
                }
              }
            }
          }
        }
      }
    },
    "/classes": {
      "get": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Query"
        ],
        "summary": "Get some or all classes",
        "responses": {
          "200": {
            "description": "Classes to be returned",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": "L5AC",
                    "class_descr": "Computer Science 5th Semester Class A"
                  },
                  {
                    "id": "L5BC",
                    "class_desc": "Computer Science 5th Semester Class A"
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Create"
        ],
        "summary": "Post a new class",
        "description": "Create a new class",
        "requestBody": {
          "required": true,
          "description": "Request body to create a new class",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Classes"
              },
              "examples": {
                "single": {
                  "value":
                    {
                      "id": "L5CC",
                      "class_desc": "Computer Science 5th Semester Class C"
                    }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Class is created",
            "content": {
              "application/json": {
                "example": {
                  "message": "The class was successfully created."
                }
              }
            }
          }
        }
      }
    },
    "/classes/{id}": {
      "parameters": [{ 
          "in": "path", 
          "name": "id", 
          "required": true,
          "description": "ID of class to fetch",
          "schema": {
            "type": "string"
          } 
          }],
       "delete": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Delete"
        ],
        "summary": "Delete a class",
        "description": "Delete a class",
        "responses": {
          "200": {
            "description": "Class is deleted",
            "content": {
              "application/json": {
                "example": {
                  "message": "The class was successfully deleted."
                }
              }
            }
          }
        }
      },
       "patch": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Patch"
        ],
        "summary": "Update a class",
        "description": "Update a class",
        "requestBody": {
          "required": true,
          "description": "Request body to update a class",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Classes"
              },
              "examples": {
                "single": {
                  "value": 
                    {
                      "id": "L5CC",
                      "class_desc": "Non-existent class"
                    }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Class is updated",
            "content": {
              "application/json": {
                "example": {
                  "message": "The class was successfully updated."
                }
              }
            }
          }
        }
      }
    },
    "/courses": {
      "get": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Query"
        ],
        "summary": "Get some or all courses",
        "responses": {
          "200": {
            "description": "Courses to be returned",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "course_id": "COMP6705001",
                    "course_name": "Distributed Systems",
                    "class_id": "L5AC",
                    "lecturer_id": "D6405"
                  },
                  {
                    "id": 2,
                    "course_id": "COMP6345001",
                    "course_name": "Intelligent Systems",
                    "class_id": "L5AC",
                    "lecturer_id": "D6211"
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Create"
        ],
        "summary": "Post a new course",
        "description": "Create a new course",
        "requestBody": {
          "required": true,
          "description": "Request body to create a new course",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Courses"
              },
              "examples": {
                "single": {
                  "value": 
                    {
                      "id": 1,
                      "course_id": "COMP6696001",
                      "course_name": "Research Methodology in Computer Science",
                      "class_id": "L5CC",
                      "lecturer_id": "D9900"
                    }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Course is created",
            "content": {
              "application/json": {
                "example": {
                  "message": "The course was successfully created."
                }
              }
            }
          }
        }
      }
    },
    "/courses/{id}": {
       "parameters": [{ 
          "in": "path", 
          "name": "id", 
          "required": true,
          "description": "ID of course to fetch",
          "schema": {
            "type": "integer"
          } 
          }],
      "delete": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Delete"
        ],
        "summary": "Delete a course",
        "description": "Delete a course",
        "responses": {
          "200": {
            "description": "Course is deleted",
            "content": {
              "application/json": {
                "example": {
                  "message": "The course was successfully deleted."
                }
              }
            }
          }
        }
      },
       "patch": {
        "security": [
          {
            "Authorization": []
          }
        ],
        "tags": [
          "Patch"
        ],
        "summary": "Update a course",
        "description": "Update a course",
        "requestBody": {
          "required": true,
          "description": "Request body to update a course",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Courses"
              },
              "examples": {
                "single": {
                  "value": 
                    {
                      "id": 1,
                      "lecturer_id": "D6211"
                    }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Course is updated",
            "content": {
              "application/json": {
                "example": {
                  "message": "The course was successfully updated."
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Authorization": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Please enter the access token."
      }
    },
    "schemas": {
      "Students": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "student_id": {
              "type": "string"
            },
            "fname": {
              "type": "string",
              "minLength": 1
            },
            "lname": {
              "type": "string",
              "minLength": 1
            },
            "email": {
              "type": "string",
              "minLength": 1
            },
            "password": {
              "type": "string",
              "minLength": 1
            },
            "phone_no": {
              "type": "string",
              "minLength": 12
            },
            "description": {
              "type": "string",
              "minLength": 1
            },
            "profile_img": {
              "type": "string",
              "minLength": 1
            },
            "class_id": {
              "type": "string"
            }
          }
        }
      },
      "Lecturers": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "lecturer_id": {
              "type": "string"
            },
            "first_name": {
              "type": "string",
              "minLength": 1
            },
            "last_name": {
              "type": "string",
              "minLength": 1
            },
            "email": {
              "type": "string",
              "minLength": 1
            },
            "password": {
              "type": "string",
              "minLength": 1
            },
            "phone_no": {
              "type": "string",
              "minLength": 12
            },
            "description": {
              "type": "string",
              "minLength": 1
            },
            "profile_img": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "Classes": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "class_id": {
              "type": "string"
            },
            "class_description": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "Courses": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "course_id": {
              "type": "string",
              "minLength": 1
            },
            "course_name": {
              "type": "string",
              "minLength": 1
            },
            "class_id": {
              "type": "string",
              "minLength": 1
            },
            "lecturer_id": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      }
    }
  }
}